---
title: "Git Notes again"
format: html
---

## basics of using git 

Git is a distributed version control system (VCS) that is very popular. 

the steps to using git involves

1. initiate a git repository 
    In R studio just click a little radio button on project creation 
    At the command line we type: 
    `git init` 
    
2. Do your normal work 
     Add files 
     Modify files etc. 
     
3. Add your important files to the "stage" 
     In Rstudio we click "stage" radio button 
     `git add yourfilename` 
     
     
4. Commit your staged filed to the repository 
      In Rstudio you just hit the " Commit" button and add a msg
      `git commit -m "your wee msg"` 
      
      
      
5. Git Push to sync changes to GitHub 
     the UP arrow in RStudio 
    `git push` 

6. Git Pull to sync from GitHub 
    the Down arrow on RStudio 
    `git pill` 

you can check your project history and status 
      `git status` 
      `git log`, (push Q to exist)
      

My AWS instances:
ssh -i ~/Downloads/bimm143_Sahar.pem ubuntu@ec2-34-214-18-211.us-west-2.compute.amazonaws.com
      
To copy from my AWS instance 
scp -i ~/Downloads/bimm143_Sahar.pem ubuntu@ec2-34-214-18-211.us-west-2.compute.amazonaws.com:~/work/results.tsv .

      
     